language: node_js
node_js: stable

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

install:
  - yarn install

script:
  - yarn build:win32

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: pages
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true