language: node_js
node_js: stable
sudo: required
dist: xenial

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

install:
  - yarn install

script:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt-key update
  - sudo apt-get update
  - sudo apt-get install -y winehq-stable
  - wine --version
  - yarn build:win32

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: pages
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true