language: node_js
node_js: stable
sudo: required
dist: xenial

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

install:
  - yarn install

script:
  - dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - apt-key add Release.key
  - apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - apt-get update
  - apt-get install --install-recommends winehq-stable
  - wine --version
  - yarn build:win32

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: pages
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true