language: node_js
node_js: stable
sudo: required
dist: xenial

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

install:
  - yarn install

script:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt update
  - sudo apt install --install-recommends winehq-stable
  - wine --version
  - export DISPLAY=:0.0
  - yarn build:win32

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: pages
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true